/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.lxisoft.crimestopper.client.red_alert.api;

import com.lxisoft.crimestopper.client.red_alert.model.ActionDTO;
import com.lxisoft.crimestopper.client.red_alert.model.OptionalOfActionDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-01-14T12:14:49.695365900+05:30[Asia/Calcutta]")

@Api(value = "ActionResource", description = "the ActionResource API")
public interface ActionResourceApi {

    @ApiOperation(value = "createAction", nickname = "createActionUsingPOST", notes = "", response = ActionDTO.class, tags={ "action-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ActionDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/apis/actions",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<ActionDTO> createActionUsingPOST(@ApiParam(value = "actionDTO" ,required=true )  @Valid @RequestBody ActionDTO actionDTO);


    @ApiOperation(value = "deleteAction", nickname = "deleteActionUsingDELETE", notes = "", tags={ "action-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/apis/actions/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteActionUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAction", nickname = "getActionUsingGET", notes = "", response = OptionalOfActionDTO.class, tags={ "action-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = OptionalOfActionDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/apis/actions/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<OptionalOfActionDTO> getActionUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllActionsByPostId", nickname = "getAllActionsByPostIdUsingGET", notes = "", response = ActionDTO.class, responseContainer = "List", tags={ "action-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ActionDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/apis/actionsByPostId/{postId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ActionDTO>> getAllActionsByPostIdUsingGET(@ApiParam(value = "postId",required=true) @PathVariable("postId") Long postId,@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "getAllActions", nickname = "getAllActionsUsingGET", notes = "", response = ActionDTO.class, responseContainer = "List", tags={ "action-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ActionDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/apis/actions",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ActionDTO>> getAllActionsUsingGET(@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "updateAction", nickname = "updateActionUsingPUT", notes = "", response = ActionDTO.class, tags={ "action-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ActionDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/apis/actions",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<ActionDTO> updateActionUsingPUT(@ApiParam(value = "actionDTO" ,required=true )  @Valid @RequestBody ActionDTO actionDTO);

}
